version: '3.8'

services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/crt:/usr/share/nginx/crt

  the-app-1:
    build: ./the-app
    environment:
      - APP_NAME="The App 1"

  the-app-2:
    build: ./the-app
    environment:
      - APP_NAME="The App 2"

  the-app-3:
    build: ./the-app
    environment:
      - APP_NAME="The App 3"